pointcloud_rotation_node:
  ros__parameters:
    sensor_rotation_y_: 0.20944   #0.174533
    voxel_condition: true
    roi_max_x_: 15.0
    roi_max_y_: 8.0
    roi_max_z_: 0.5
    roi_min_x_: -0.5
    roi_min_y_: -8.0
    roi_min_z_: -2.5
    voxel_leaf_size_x: 0.1
    voxel_leaf_size_y: 0.1
    voxel_leaf_size_z: 0.1
    num_seg_: 25
    num_iter_: 15
    num_lpr_: 400
    th_seeds_: 0.3
    th_dist_: 0.3
    sensor_height_: 1.93